import 'server-only';
import { ensureOccurrences } from './data';
import { ensureInventoryInstances } from './inventory';
import { addDays, businessToday, type BusinessDate } from '@/lib/datetime';
import { createClient } from '@/lib/supabase/server';

/**
 * Materialising scheduled work — one entry point, one owner.
 *
 * Task occurrences and inventory instances are generated by structurally
 * identical code: load the active definitions, skip the unconfigured ones,
 * run a pure generator, ignoring-upsert on a natural key with the service
 * role. What they did not share was a caller.
 *
 * Generation used to happen as a SIDE EFFECT OF RENDERING: the dashboard
 * generated 7 days of tasks, the calendar generated whatever month you
 * navigated to, and the inventory dashboard generated 1 day when called from
 * the dashboard and 21 when called from its own screen. Five unrelated
 * horizons meant whether Monday's inventory existed depended on who opened
 * which page over the weekend.
 *
 * Now the cron route owns it and pages only read. The one deliberate
 * exception is the calendar — see ensureCalendarWindow below.
 */

export const HORIZON_DAYS = {
  /** Task occurrences. The dashboard, notifier and reports all read inside this. */
  tasks: 60,
  /**
   * Inventories. Longer, because a semiannual count has to appear on the
   * calendar well before 30 June, whereas a daily task never does.
   */
  inventories: 120,
  /**
   * Re-materialise yesterday as well, so a definition activated late in the
   * day still produces the requirement it was meant to produce.
   */
  lookBack: 1,
} as const;

export interface ScheduleRun {
  today: BusinessDate;
  tasks: { created: number; skippedTasks: number };
  inventories: { created: number; skippedTemplates: number };
}

/**
 * Materialise both kinds of scheduled work.
 *
 * Idempotent in both halves — the UNIQUE constraints plus an ignoring upsert
 * mean a retried, overlapping or duplicated run can never create a second
 * record or overwrite one that already carries entered data. That property is
 * what makes it safe to call this from a cron, a button and a test.
 */
export async function ensureScheduled(
  taskDays: number = HORIZON_DAYS.tasks,
  inventoryDays: number = HORIZON_DAYS.inventories,
): Promise<ScheduleRun> {
  const today = businessToday();
  const from = addDays(today, -HORIZON_DAYS.lookBack);

  // Run together: neither depends on the other, and a slow inventory pass
  // should not delay task generation.
  const [tasks, inventories] = await Promise.all([
    ensureOccurrences(from, addDays(today, taskDays)),
    ensureInventoryInstances(from, addDays(today, inventoryDays)),
  ]);

  return { today, tasks, inventories };
}

/**
 * The calendar's on-demand window.
 *
 * The one place a page may still generate, and for a reason the cron cannot
 * cover: the calendar navigates to arbitrary months, including ones beyond
 * any fixed horizon. Browsing to next March must show what is scheduled in
 * next March rather than an empty grid.
 *
 * Tasks only — the calendar renders occurrences, not inventories.
 */
export async function ensureCalendarWindow(from: BusinessDate, to: BusinessDate) {
  return ensureOccurrences(from, to);
}

/**
 * Is anything actually materialised beyond today?
 *
 * Pages no longer generate, so a cron that has silently stopped would show up
 * as a dashboard that quietly empties out over a few days. This is the check
 * that turns that into a visible warning on the admin overview instead.
 */
export async function getScheduleHealth(): Promise<{
  futureOccurrences: number;
  futureInventories: number;
  /** True when definitions exist to schedule but nothing ahead was created. */
  stalled: boolean;
}> {
  const supabase = createClient();
  const today = businessToday();

  const [occurrences, inventories, activeTasks] = await Promise.all([
    supabase
      .from('task_occurrences')
      .select('id', { count: 'exact', head: true })
      .gt('effective_due_date', today),
    supabase
      .from('inventory_instances')
      .select('id', { count: 'exact', head: true })
      .gt('inventory_date', today),
    supabase
      .from('tasks')
      .select('id', { count: 'exact', head: true })
      .eq('is_active', true),
  ]);

  const futureOccurrences = occurrences.count ?? 0;
  const futureInventories = inventories.count ?? 0;

  return {
    futureOccurrences,
    futureInventories,
    // Only a warning when there is work that SHOULD have been materialised.
    // A brand-new system with no tasks is not stalled, it is empty.
    stalled: (activeTasks.count ?? 0) > 0 && futureOccurrences === 0,
  };
}
